name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: a
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - name: b
        uses: actions/checkout@v2

      - name: c
        run: go mod download

      - name: d
        run: go build
      
      - name: c
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ github.event.repository.name }}:latest, ${{ github.repository }}:latest

          
        
