name: to hub

on:
  push:
    tags:
      - "*.*.*"

jobs:
  to:
    runs-on: ubuntu-latest
    steps:
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - name: load code
        uses: actions/checkout@v2

      - name: fetch dep
        run: go mod download

      - name: build
        run: go build -v

      - name: push
        id: push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: info
        run: echo ${{ steps.build.outputs.digest }}
